events { worker_connections 1024; }

http {
    server {
        listen 80;

        location / {
            proxy_pass http://ims_frontend:80;
            proxy_set_header Host $host;
        }

        location /api {
            proxy_pass http://ims_backend:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            proxy_pass http://ims_backend:8000;
        }

        location /docs {
            proxy_pass http://ims_backend:8000;
        }

        location /openapi.json {
            proxy_pass http://ims_backend:8000;
        }
    }
}
